### ISSUE TITLE
Several issues with the Storage I/O Extension

### ISSUE THREAD

**Issue by Belgabor** [TeamCoS/Modular-Systems#101]
1. Filter items can be pulled out/inserted by automation. E. g. put a hopper below and it will pull out the filter items. If this is intended, please provide a toggle on the interface to switch this behavior =)
2. I have crashed related to the I/O. I'm about 95% sure it happens when you place the I/O down first and then connect it to the system, although I'm not sure it happens always.

Crash report: http://pastebin.com/sBdU3h48

**Comment by pauljoda** [comment]
I am aware of the issue. I've tried fixing it before but it's very strange. As for the automation, since it pushes and pulls from the main inventory, automation occurs on its own inventory. I only want one face to do the movement so I don't think I'll add a toggle. I have to keep some balance to it.

**Comment by Belgabor** [comment]
Well, then please at least disallow interaction via the active face. For example you can't push stuff with a filter into a hopper below it as the hopper will pull out the filter item.
