### ISSUE TITLE
Crash with modular systems on 1.7.10

### ISSUE THREAD

**Issue by 23Link89** [TeamCoS/Modular-Systems#128]
Crash with Slimevoid Library on Forge .1614
Slimevoid Ver: 2.0.4.7
Modular Systems ver: 2.2.1
Minecraft Version: 1.7.10
Crash: http://pastebin.com/L8MfNbv5

**Comment by pauljoda** [comment]
We no longer support 1.7.10

**Comment by JamesKoenig** [comment]
I experienced the same crash related to Modular Systems today
Modular systems ver 2.2.1
Minecraft Version: 1.7.10
http://pastebin.com/PKGfmNtB

This was while trying to start the Galactic Science modpack, disabling modular systems allowed me to run the overall modpack fine without it, so the issue was purely with modular systems.

For some reason Java throws a null pointer exception while trying to write to ModularSystems.cfg, which also results in the config file being wiped (turned into empty 0kb file).  From the source

**Comment by JamesKoenig** [comment]
oh you no longer support 1.7.10, cool

**Comment by pauljoda** [comment]
Sorry about that, we just can't run so many different versions. We will stay on the latest stable forge, which right now is 1.10.2

**Comment by JamesKoenig** [comment]
Sorry if I sounded curt, I wrote the 'cool' comment because the ticket closed right as I hit send on my reply, which surprised me.

Thanks for the mod, the support, and everything.  I appreciate it.
