### ISSUE TITLE
Furnace & Crusher issues

### ISSUE THREAD

**Issue by luca020400** [TeamCoS/Modular-Systems#75]
1) I have two systems with different size made of lapis lazzuli (1 Furnace core  2 I/O Port & RedstoneFlux Port )
Furnace 1 --> 5 * 5 * 6 --> Speed 12.50% / Efficiency 25%
Furnace 2 --> 7 * 9 * 11 --> Speed 12.50% / Efficiency 25%

2) My modular Furnace made of lapis lazzuli ( 7*9*11 ) has the same speed (in ticks) as the vanilla
 furnace --> https://youtu.be/v717edHb8yE

Same thing happens with crusher

**Comment by pauljoda** [comment]
I don't believe this is an issue. Each type of block has a cap, once you hit it no matter how large you can't get more out of it. Lapis doesn't give much anyway so those numbers make sense. Also, that speed is faster than vanilla. I don't see how you're saying it's the same. It's barely faster, but it's faster. I've taken your build with the same numbers, set a vanilla furnace next to it, and had them start at the same time. Ours was faster. I'm closing this because I don't think there is anything wrong, in fact, things are behaving just as they should.

**Comment by luca020400** [comment]
Is there any way to remove the cap ?

**Comment by pauljoda** [comment]
Type /configureBlockValues and you can raise or lower the cap. There is a ceiling and a floor value. Depending on the functions, you'll need to edit one of those
