### ISSUE TITLE
Feature Requests from original version thread

### ISSUE THREAD

**Issue by drz2k** [TeamCoS/Modular-Systems#90]
Hey there, we made some feature requests on the original thread (before he went off to make another random bags mod) we would really like to see coming in. I would love to see them come in and finally have an alternative to the overused (but ofc awesome) AE2.

Ill copy and paste them below : 

Problems and suggestions:

- Stacks take up more than 1 space, so can you plz make it so that you can change that in the configs

- There is no search bar, so please add a block that can allow you to search

- There is a limit on how much storage expansion blocks you can have (Tested about 440 storage spaces w/ all the upgrades)

- You cannot use the mouse scroll wheel to scroll down ( abit annoying)

- Crafting Table does not save when you exit the GUI

- Should have more compact but more expensive blocks that add more storage space

Cheers drz2k aka Caithleen

**Comment by pauljoda** [comment]
You'll probably like the new system then. Let me tackle these one by one
-There will never be greater stack sizes. This is a giant chest. Its not like AE where you items are converted to data. The items physically reside in the blocks and that is why you can't have stack sizes bigger than they should be
-There is now a search bar. You can even use '@' to search by mod
-There is no longer a limit
-You can, and always have been able to use the scroll wheel. The reason I believe you think you can't is your mouse has to be outside the slot area. Because NEI adds functions to use the scroll wheel to move items in and out, I've disabled it from moving the scroll bar when over an item. Just move the mouse to the side and you'll see it work.
-The crafting grid now remembers its inventory
-I probably won't make compact blocks. Its not that it would be hard (it would take me 10 minutes) but I don't want to make this too overpowered without a drawback. The largest drawback you have is space. You have to plan an area for it and that makes it feel more realistic. I know it can be a bit annoying, but I have to keep the balance and idea of the mod throughout all parts. I am still considering it though

I know you weren't happy about my grabbag mod. For one, I haven't been in the mod for ages. I spent maybe a week coding that before I got into this. The entire mod is now completely rewritten and 100x better than the old version. The storage system will be released in the next update which should be very soon if testing goes well. When that comes, I encourage you to try it out and let me know what you think. You are very detailed in your features so I would love to hear what else you have to say. You can even try it now if you know how to use the source here

**Comment by drz2k** [comment]
That sounds good and im looking forward. Thoo, do you have an idea how your system could handle high volume stuff better?

Our pack uses minechem which essentially is multiplying things *16 in its chemical form. (One iron = 16 FE) which leads to pages after pages after pages of FE shown in the storage.

**Comment by pauljoda** [comment]
I can understand your problem. I really do. However I can think of any way to help in that regard without changed the fact that this is a chest. Not energy like ae. You can have a separate system for them than the others, but I can think of a way to make it better but still balanced. If you think of something let me know

**Comment by drz2k** [comment]
Perhaps a JABBA integration? Like the storage busses from AE, instead something that fits the mod like item pumps. Or the other way round - a way to use blocks form the system like a barrel for mass item movement.

**Comment by pauljoda** [comment]
Perhaps down the line. I'm not apposed to the idea, but I don't think the system is to that level yet. I can handle it, but since it is so new and written totally different from the last version I would like some time to let this one out and see if anything breaks. I'll keep this in the back of my mind though
